name: Test
permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call Dagger Function
        uses: dagger/dagger-for-github@v6
        with:
          version: "v0.19.11"
          verb: call
          args: -m dagger test --source=.
